---
- name: install nginx
  apt:
    name: nginx
    state: installed
  notify:
    - start nginx

- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx

- name: enable nginx in ufw
  ufw:
    rule: allow
    name: 'Nginx Full'
  notify:
    - enable ufw