---
- hosts: webservers
  roles:
    - nginx
    - docker
    - role: ssl
      site_domain: rasband.io
      server_port: 5001
    - role: ssl
      site_domain: rockymountainpy.com
      server_port: 5000
    - role: ssl
      site_domain: bootiful.io
      server_port: 8080
    - role: ssl
      site_domain: staging.ottter.com
      server_port: 8000
      static_dir: /var/www/staging.ottter.com/collected-static/

- hosts: pythonremoteconf
  roles:
    - nginx
    - role: ssl
      site_domain: pythonremoteconf.com
      server_port: 8000
      static_dir: /var/www/pythonremoteconf.com/collected-static/
