---
- name: add the deadsnakes ppa
  apt_repository:
    repo: ppa:fkrull/deadsnakes
    update_cache: yes

- name: install python 3
  apt:
    package: "{{ item }}"
    state: latest
  with_items:
    - python3.6
    - python3-pip

- name: install virtualenv
  pip:
    name: virtualenv
